[build]
builder = "NIXPACKS"
 
[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]
 
[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
